services:
  journal-web:
    container_name: journal-web
    build:
      context: ./journal-web
      target: runner
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3001
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - ogsdell-network

networks:
  ogsdell-network:
    external: true
    name: ogsdell-network
